image: microsoft/dotnet:latest

stages:
  - build

variables:
  project: "Heroes.ReplayParser"

before_script:
  - "dotnet restore"

build:
  stage: build
  variables:
    build_path: "$project"
  script:
    - "cd $build_path"
    - "dotnet build Heroes.ReplayParser.netstandard.csproj"