image: microsoft/dotnet:latest

stages:
  - deploy

variables:
  project: "Heroes.ReplayParser"

before_script:
  - "dotnet restore"

build:
  stage: deploy
  variables:
    build_path: "$project"
  script:
    - "cd $build_path"
    - "dotnet build Heroes.ReplayParser.netstandard.csproj"
    - "dotnet pack Heroes.ReplayParser.netstandard.csproj"
    - "dotnet nuget push bin/Debug/$project.netstandard.1.0.0.nupkg --api-key=$nuget_api_key"
