image: microsoft/dotnet:latest

stages:
  - deploy

variables:
  parser: "Heroes.ReplayParser"
  mpq: "MpqTool"

before_script:
  - "dotnet restore"

build:
  stage: deploy
  script:
    - "dotnet pack $parser/Heroes.ReplayParser.netstandard.csproj"
    - "dotnet pack $mpq/MpqTool.netstandard.csproj"
    - "dotnet nuget push **/*.nupkg --source=https://api.nuget.org/v3/index.json --api-key=$nuget_api_key"
